//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sportsmen_Monitoring.ServiceConnectServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Goals", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Goals : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisciplineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PeriodDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Standart_Data[] Standart_DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Users_Goals[] Users_GoalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DisciplineId {
            get {
                return this.DisciplineIdField;
            }
            set {
                if ((this.DisciplineIdField.Equals(value) != true)) {
                    this.DisciplineIdField = value;
                    this.RaisePropertyChanged("DisciplineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public short PeriodDays {
            get {
                return this.PeriodDaysField;
            }
            set {
                if ((this.PeriodDaysField.Equals(value) != true)) {
                    this.PeriodDaysField = value;
                    this.RaisePropertyChanged("PeriodDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Sportsmen_Monitoring.ServiceConnectServer.Standart_Data[] Standart_Data {
            get {
                return this.Standart_DataField;
            }
            set {
                if ((object.ReferenceEquals(this.Standart_DataField, value) != true)) {
                    this.Standart_DataField = value;
                    this.RaisePropertyChanged("Standart_Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Goals[] Users_Goals {
            get {
                return this.Users_GoalsField;
            }
            set {
                if ((object.ReferenceEquals(this.Users_GoalsField, value) != true)) {
                    this.Users_GoalsField = value;
                    this.RaisePropertyChanged("Users_Goals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Standart_Data", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Standart_Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int GoalId {
            get {
                return this.GoalIdField;
            }
            set {
                if ((this.GoalIdField.Equals(value) != true)) {
                    this.GoalIdField = value;
                    this.RaisePropertyChanged("GoalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public short Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users_Goals", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Users_Goals : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Users_Data[] Users_DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int GoalId {
            get {
                return this.GoalIdField;
            }
            set {
                if ((this.GoalIdField.Equals(value) != true)) {
                    this.GoalIdField = value;
                    this.RaisePropertyChanged("GoalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DateStart {
            get {
                return this.DateStartField;
            }
            set {
                if ((this.DateStartField.Equals(value) != true)) {
                    this.DateStartField = value;
                    this.RaisePropertyChanged("DateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Data[] Users_Data {
            get {
                return this.Users_DataField;
            }
            set {
                if ((object.ReferenceEquals(this.Users_DataField, value) != true)) {
                    this.Users_DataField = value;
                    this.RaisePropertyChanged("Users_Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users_Data", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Users_Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_GoalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int User_GoalId {
            get {
                return this.User_GoalIdField;
            }
            set {
                if ((this.User_GoalIdField.Equals(value) != true)) {
                    this.User_GoalIdField = value;
                    this.RaisePropertyChanged("User_GoalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronumicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AspnetUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoachIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Goals[] GoalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Users_Goals[] Users_GoalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Patronumic {
            get {
                return this.PatronumicField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronumicField, value) != true)) {
                    this.PatronumicField = value;
                    this.RaisePropertyChanged("Patronumic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Guid AspnetUserId {
            get {
                return this.AspnetUserIdField;
            }
            set {
                if ((this.AspnetUserIdField.Equals(value) != true)) {
                    this.AspnetUserIdField = value;
                    this.RaisePropertyChanged("AspnetUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DateBirth {
            get {
                return this.DateBirthField;
            }
            set {
                if ((this.DateBirthField.Equals(value) != true)) {
                    this.DateBirthField = value;
                    this.RaisePropertyChanged("DateBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int CoachId {
            get {
                return this.CoachIdField;
            }
            set {
                if ((this.CoachIdField.Equals(value) != true)) {
                    this.CoachIdField = value;
                    this.RaisePropertyChanged("CoachId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte Right {
            get {
                return this.RightField;
            }
            set {
                if ((this.RightField.Equals(value) != true)) {
                    this.RightField = value;
                    this.RaisePropertyChanged("Right");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Sportsmen_Monitoring.ServiceConnectServer.Goals[] Goals {
            get {
                return this.GoalsField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalsField, value) != true)) {
                    this.GoalsField = value;
                    this.RaisePropertyChanged("Goals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Goals[] Users_Goals {
            get {
                return this.Users_GoalsField;
            }
            set {
                if ((object.ReferenceEquals(this.Users_GoalsField, value) != true)) {
                    this.Users_GoalsField = value;
                    this.RaisePropertyChanged("Users_Goals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Users", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class aspnet_Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAnonymousField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastActivityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.aspnet_Membership aspnet_MembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.aspnet_PersonalizationPerUser[] aspnet_PersonalizationPerUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.aspnet_Profile aspnet_ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.aspnet_UsersInRoles[] aspnet_UsersInRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Users[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string MobileAlias {
            get {
                return this.MobileAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileAliasField, value) != true)) {
                    this.MobileAliasField = value;
                    this.RaisePropertyChanged("MobileAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsAnonymous {
            get {
                return this.IsAnonymousField;
            }
            set {
                if ((this.IsAnonymousField.Equals(value) != true)) {
                    this.IsAnonymousField = value;
                    this.RaisePropertyChanged("IsAnonymous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime LastActivityDate {
            get {
                return this.LastActivityDateField;
            }
            set {
                if ((this.LastActivityDateField.Equals(value) != true)) {
                    this.LastActivityDateField = value;
                    this.RaisePropertyChanged("LastActivityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Sportsmen_Monitoring.ServiceConnectServer.aspnet_Membership aspnet_Membership {
            get {
                return this.aspnet_MembershipField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_MembershipField, value) != true)) {
                    this.aspnet_MembershipField = value;
                    this.RaisePropertyChanged("aspnet_Membership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Sportsmen_Monitoring.ServiceConnectServer.aspnet_PersonalizationPerUser[] aspnet_PersonalizationPerUser {
            get {
                return this.aspnet_PersonalizationPerUserField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PersonalizationPerUserField, value) != true)) {
                    this.aspnet_PersonalizationPerUserField = value;
                    this.RaisePropertyChanged("aspnet_PersonalizationPerUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Sportsmen_Monitoring.ServiceConnectServer.aspnet_Profile aspnet_Profile {
            get {
                return this.aspnet_ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ProfileField, value) != true)) {
                    this.aspnet_ProfileField = value;
                    this.RaisePropertyChanged("aspnet_Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Sportsmen_Monitoring.ServiceConnectServer.aspnet_UsersInRoles[] aspnet_UsersInRoles {
            get {
                return this.aspnet_UsersInRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersInRolesField, value) != true)) {
                    this.aspnet_UsersInRolesField = value;
                    this.RaisePropertyChanged("aspnet_UsersInRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public Sportsmen_Monitoring.ServiceConnectServer.Users[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Membership", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class aspnet_Membership : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasswordFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPasswordChangedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLockoutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailedPasswordAttemptCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FailedPasswordAttemptWindowStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailedPasswordAnswerAttemptCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FailedPasswordAnswerAttemptWindowStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int PasswordFormat {
            get {
                return this.PasswordFormatField;
            }
            set {
                if ((this.PasswordFormatField.Equals(value) != true)) {
                    this.PasswordFormatField = value;
                    this.RaisePropertyChanged("PasswordFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string MobilePIN {
            get {
                return this.MobilePINField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePINField, value) != true)) {
                    this.MobilePINField = value;
                    this.RaisePropertyChanged("MobilePIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string LoweredEmail {
            get {
                return this.LoweredEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredEmailField, value) != true)) {
                    this.LoweredEmailField = value;
                    this.RaisePropertyChanged("LoweredEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PasswordQuestion {
            get {
                return this.PasswordQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordQuestionField, value) != true)) {
                    this.PasswordQuestionField = value;
                    this.RaisePropertyChanged("PasswordQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string PasswordAnswer {
            get {
                return this.PasswordAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordAnswerField, value) != true)) {
                    this.PasswordAnswerField = value;
                    this.RaisePropertyChanged("PasswordAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool IsApproved {
            get {
                return this.IsApprovedField;
            }
            set {
                if ((this.IsApprovedField.Equals(value) != true)) {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.DateTime LastLoginDate {
            get {
                return this.LastLoginDateField;
            }
            set {
                if ((this.LastLoginDateField.Equals(value) != true)) {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.DateTime LastPasswordChangedDate {
            get {
                return this.LastPasswordChangedDateField;
            }
            set {
                if ((this.LastPasswordChangedDateField.Equals(value) != true)) {
                    this.LastPasswordChangedDateField = value;
                    this.RaisePropertyChanged("LastPasswordChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.DateTime LastLockoutDate {
            get {
                return this.LastLockoutDateField;
            }
            set {
                if ((this.LastLockoutDateField.Equals(value) != true)) {
                    this.LastLockoutDateField = value;
                    this.RaisePropertyChanged("LastLockoutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int FailedPasswordAttemptCount {
            get {
                return this.FailedPasswordAttemptCountField;
            }
            set {
                if ((this.FailedPasswordAttemptCountField.Equals(value) != true)) {
                    this.FailedPasswordAttemptCountField = value;
                    this.RaisePropertyChanged("FailedPasswordAttemptCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.DateTime FailedPasswordAttemptWindowStart {
            get {
                return this.FailedPasswordAttemptWindowStartField;
            }
            set {
                if ((this.FailedPasswordAttemptWindowStartField.Equals(value) != true)) {
                    this.FailedPasswordAttemptWindowStartField = value;
                    this.RaisePropertyChanged("FailedPasswordAttemptWindowStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public int FailedPasswordAnswerAttemptCount {
            get {
                return this.FailedPasswordAnswerAttemptCountField;
            }
            set {
                if ((this.FailedPasswordAnswerAttemptCountField.Equals(value) != true)) {
                    this.FailedPasswordAnswerAttemptCountField = value;
                    this.RaisePropertyChanged("FailedPasswordAnswerAttemptCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.DateTime FailedPasswordAnswerAttemptWindowStart {
            get {
                return this.FailedPasswordAnswerAttemptWindowStartField;
            }
            set {
                if ((this.FailedPasswordAnswerAttemptWindowStartField.Equals(value) != true)) {
                    this.FailedPasswordAnswerAttemptWindowStartField = value;
                    this.RaisePropertyChanged("FailedPasswordAnswerAttemptWindowStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Profile", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class aspnet_Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyValuesStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Binary PropertyValuesBinaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string PropertyNames {
            get {
                return this.PropertyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNamesField, value) != true)) {
                    this.PropertyNamesField = value;
                    this.RaisePropertyChanged("PropertyNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PropertyValuesString {
            get {
                return this.PropertyValuesStringField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyValuesStringField, value) != true)) {
                    this.PropertyValuesStringField = value;
                    this.RaisePropertyChanged("PropertyValuesString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Sportsmen_Monitoring.ServiceConnectServer.Binary PropertyValuesBinary {
            get {
                return this.PropertyValuesBinaryField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyValuesBinaryField, value) != true)) {
                    this.PropertyValuesBinaryField = value;
                    this.RaisePropertyChanged("PropertyValuesBinary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_PersonalizationPerUser", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class aspnet_PersonalizationPerUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PathIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Binary PageSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PathId {
            get {
                return this.PathIdField;
            }
            set {
                if ((this.PathIdField.Equals(value) != true)) {
                    this.PathIdField = value;
                    this.RaisePropertyChanged("PathId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Sportsmen_Monitoring.ServiceConnectServer.Binary PageSettings {
            get {
                return this.PageSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.PageSettingsField, value) != true)) {
                    this.PageSettingsField = value;
                    this.RaisePropertyChanged("PageSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_UsersInRoles", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class aspnet_UsersInRoles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MembershipCreateStatus", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Security")]
    public enum MembershipCreateStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidQuestion = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAnswer = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateUserName = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateEmail = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserRejected = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidProviderUserKey = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateProviderUserKey = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderError = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sports", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Sports : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Discipline[] DisciplineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Sportsmen_Monitoring.ServiceConnectServer.Discipline[] Discipline {
            get {
                return this.DisciplineField;
            }
            set {
                if ((object.ReferenceEquals(this.DisciplineField, value) != true)) {
                    this.DisciplineField = value;
                    this.RaisePropertyChanged("Discipline");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Discipline", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Discipline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScaleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Goals[] GoalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportId {
            get {
                return this.SportIdField;
            }
            set {
                if ((this.SportIdField.Equals(value) != true)) {
                    this.SportIdField = value;
                    this.RaisePropertyChanged("SportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ScaleId {
            get {
                return this.ScaleIdField;
            }
            set {
                if ((this.ScaleIdField.Equals(value) != true)) {
                    this.ScaleIdField = value;
                    this.RaisePropertyChanged("ScaleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Sportsmen_Monitoring.ServiceConnectServer.Goals[] Goals {
            get {
                return this.GoalsField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalsField, value) != true)) {
                    this.GoalsField = value;
                    this.RaisePropertyChanged("Goals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scales", Namespace="http://schemas.datacontract.org/2004/07/ServiceSportsmens")]
    [System.SerializableAttribute()]
    public partial class Scales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sportsmen_Monitoring.ServiceConnectServer.Discipline[] DisciplineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Sportsmen_Monitoring.ServiceConnectServer.Discipline[] Discipline {
            get {
                return this.DisciplineField;
            }
            set {
                if ((object.ReferenceEquals(this.DisciplineField, value) != true)) {
                    this.DisciplineField = value;
                    this.RaisePropertyChanged("Discipline");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceConnectServer.IServiceData")]
    public interface IServiceData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetGoalsFromDiscipline", ReplyAction="http://tempuri.org/IServiceData/GetGoalsFromDisciplineResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Goals[] GetGoalsFromDiscipline(int disciplineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetUsers_GoalsFromUser", ReplyAction="http://tempuri.org/IServiceData/GetUsers_GoalsFromUserResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Goals[] GetUsers_GoalsFromUser(int userId, int goalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetUsersFromGoal", ReplyAction="http://tempuri.org/IServiceData/GetUsersFromGoalResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users[] GetUsersFromGoal(int goalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddCoachToUser", ReplyAction="http://tempuri.org/IServiceData/AddCoachToUserResponse")]
        bool AddCoachToUser(int userId, int coachId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/SetUserCoach", ReplyAction="http://tempuri.org/IServiceData/SetUserCoachResponse")]
        bool SetUserCoach(int userId, bool isCoach);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetUsers_GoalsFromUserAndDiscipline", ReplyAction="http://tempuri.org/IServiceData/GetUsers_GoalsFromUserAndDisciplineResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Goals GetUsers_GoalsFromUserAndDiscipline(int userId, int disciplineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetStandart_DataFromGoal", ReplyAction="http://tempuri.org/IServiceData/GetStandart_DataFromGoalResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Standart_Data[] GetStandart_DataFromGoal(int goalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetUsers_DataFromGoal", ReplyAction="http://tempuri.org/IServiceData/GetUsers_DataFromGoalResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Data[] GetUsers_DataFromGoal(int goalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetAllCoachs", ReplyAction="http://tempuri.org/IServiceData/GetAllCoachsResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users[] GetAllCoachs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/Getaspnet_Users", ReplyAction="http://tempuri.org/IServiceData/Getaspnet_UsersResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.aspnet_Users Getaspnet_Users(System.Guid aspnetuserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetUserFromLogin", ReplyAction="http://tempuri.org/IServiceData/GetUserFromLoginResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users GetUserFromLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/Auth", ReplyAction="http://tempuri.org/IServiceData/AuthResponse")]
        bool Auth(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AuthSuperAdmin", ReplyAction="http://tempuri.org/IServiceData/AuthSuperAdminResponse")]
        bool AuthSuperAdmin(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddUser", ReplyAction="http://tempuri.org/IServiceData/AddUserResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users AddUser(out Sportsmen_Monitoring.ServiceConnectServer.MembershipCreateStatus status, string firstName, string name, string patronumic, System.DateTime dateBirth, string login, string pass, int coachId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditUser", ReplyAction="http://tempuri.org/IServiceData/EditUserResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users EditUser(int userId, string firstName, string name, string patronumic, System.DateTime dateBirth, int coachId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteUser", ReplyAction="http://tempuri.org/IServiceData/DeleteUserResponse")]
        bool DeleteUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddSport", ReplyAction="http://tempuri.org/IServiceData/AddSportResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Sports AddSport(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditSport", ReplyAction="http://tempuri.org/IServiceData/EditSportResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Sports EditSport(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteSport", ReplyAction="http://tempuri.org/IServiceData/DeleteSportResponse")]
        bool DeleteSport(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddDiscipline", ReplyAction="http://tempuri.org/IServiceData/AddDisciplineResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Discipline AddDiscipline(string name, int sportId, int scaleId, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditDiscipline", ReplyAction="http://tempuri.org/IServiceData/EditDisciplineResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Discipline EditDiscipline(int disciplineId, string name, int sportId, int scaleId, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteDiscipline", ReplyAction="http://tempuri.org/IServiceData/DeleteDisciplineResponse")]
        bool DeleteDiscipline(int disciplineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddGoal", ReplyAction="http://tempuri.org/IServiceData/AddGoalResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Goals AddGoal(int disciplineId, short periodDays, double value, string description, int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditGoal", ReplyAction="http://tempuri.org/IServiceData/EditGoalResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Goals EditGoal(int GoalId, int disciplineId, short periodDays, double value, string description, int ownerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteGoal", ReplyAction="http://tempuri.org/IServiceData/DeleteGoalResponse")]
        bool DeleteGoal(int GoalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddUsers_Goals", ReplyAction="http://tempuri.org/IServiceData/AddUsers_GoalsResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Goals AddUsers_Goals(int userId, int goalId, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditUsers_Goals", ReplyAction="http://tempuri.org/IServiceData/EditUsers_GoalsResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Goals EditUsers_Goals(int Users_GoalsId, int userId, int goalId, System.DateTime dateStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteUsers_Goals", ReplyAction="http://tempuri.org/IServiceData/DeleteUsers_GoalsResponse")]
        bool DeleteUsers_Goals(int Users_GoalsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddUsers_Data", ReplyAction="http://tempuri.org/IServiceData/AddUsers_DataResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Data AddUsers_Data(int user_goalId, System.DateTime date, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditUsers_Data", ReplyAction="http://tempuri.org/IServiceData/EditUsers_DataResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users_Data EditUsers_Data(int user_dataId, int user_goalId, System.DateTime date, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteUsers_Data", ReplyAction="http://tempuri.org/IServiceData/DeleteUsers_DataResponse")]
        bool DeleteUsers_Data(int user_dataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddStandart_Data", ReplyAction="http://tempuri.org/IServiceData/AddStandart_DataResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Standart_Data AddStandart_Data(double value, int goalId, short day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/EditStandart_Data", ReplyAction="http://tempuri.org/IServiceData/EditStandart_DataResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Standart_Data EditStandart_Data(int standart_dataId, double value, int goalId, short day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteStandart_Data", ReplyAction="http://tempuri.org/IServiceData/DeleteStandart_DataResponse")]
        bool DeleteStandart_Data(int standart_dataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetAllUsers", ReplyAction="http://tempuri.org/IServiceData/GetAllUsersResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetUserFromId", ReplyAction="http://tempuri.org/IServiceData/GetUserFromIdResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Users GetUserFromId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetAllScales", ReplyAction="http://tempuri.org/IServiceData/GetAllScalesResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Scales[] GetAllScales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetAllSports", ReplyAction="http://tempuri.org/IServiceData/GetAllSportsResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Sports[] GetAllSports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetDiscipliniesFromSport", ReplyAction="http://tempuri.org/IServiceData/GetDiscipliniesFromSportResponse")]
        Sportsmen_Monitoring.ServiceConnectServer.Discipline[] GetDiscipliniesFromSport(int sportId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDataChannel : Sportsmen_Monitoring.ServiceConnectServer.IServiceData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDataClient : System.ServiceModel.ClientBase<Sportsmen_Monitoring.ServiceConnectServer.IServiceData>, Sportsmen_Monitoring.ServiceConnectServer.IServiceData {
        
        public ServiceDataClient() {
        }
        
        public ServiceDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Goals[] GetGoalsFromDiscipline(int disciplineId) {
            return base.Channel.GetGoalsFromDiscipline(disciplineId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Goals[] GetUsers_GoalsFromUser(int userId, int goalId) {
            return base.Channel.GetUsers_GoalsFromUser(userId, goalId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users[] GetUsersFromGoal(int goalId) {
            return base.Channel.GetUsersFromGoal(goalId);
        }
        
        public bool AddCoachToUser(int userId, int coachId) {
            return base.Channel.AddCoachToUser(userId, coachId);
        }
        
        public bool SetUserCoach(int userId, bool isCoach) {
            return base.Channel.SetUserCoach(userId, isCoach);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Goals GetUsers_GoalsFromUserAndDiscipline(int userId, int disciplineId) {
            return base.Channel.GetUsers_GoalsFromUserAndDiscipline(userId, disciplineId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Standart_Data[] GetStandart_DataFromGoal(int goalId) {
            return base.Channel.GetStandart_DataFromGoal(goalId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Data[] GetUsers_DataFromGoal(int goalId) {
            return base.Channel.GetUsers_DataFromGoal(goalId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users[] GetAllCoachs() {
            return base.Channel.GetAllCoachs();
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.aspnet_Users Getaspnet_Users(System.Guid aspnetuserId) {
            return base.Channel.Getaspnet_Users(aspnetuserId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users GetUserFromLogin(string login) {
            return base.Channel.GetUserFromLogin(login);
        }
        
        public bool Auth(string login, string pass) {
            return base.Channel.Auth(login, pass);
        }
        
        public bool AuthSuperAdmin(string login, string pass) {
            return base.Channel.AuthSuperAdmin(login, pass);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users AddUser(out Sportsmen_Monitoring.ServiceConnectServer.MembershipCreateStatus status, string firstName, string name, string patronumic, System.DateTime dateBirth, string login, string pass, int coachId) {
            return base.Channel.AddUser(out status, firstName, name, patronumic, dateBirth, login, pass, coachId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users EditUser(int userId, string firstName, string name, string patronumic, System.DateTime dateBirth, int coachId) {
            return base.Channel.EditUser(userId, firstName, name, patronumic, dateBirth, coachId);
        }
        
        public bool DeleteUser(int userId) {
            return base.Channel.DeleteUser(userId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Sports AddSport(string name) {
            return base.Channel.AddSport(name);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Sports EditSport(int id, string name) {
            return base.Channel.EditSport(id, name);
        }
        
        public bool DeleteSport(int id) {
            return base.Channel.DeleteSport(id);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Discipline AddDiscipline(string name, int sportId, int scaleId, string description) {
            return base.Channel.AddDiscipline(name, sportId, scaleId, description);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Discipline EditDiscipline(int disciplineId, string name, int sportId, int scaleId, string description) {
            return base.Channel.EditDiscipline(disciplineId, name, sportId, scaleId, description);
        }
        
        public bool DeleteDiscipline(int disciplineId) {
            return base.Channel.DeleteDiscipline(disciplineId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Goals AddGoal(int disciplineId, short periodDays, double value, string description, int ownerId) {
            return base.Channel.AddGoal(disciplineId, periodDays, value, description, ownerId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Goals EditGoal(int GoalId, int disciplineId, short periodDays, double value, string description, int ownerId) {
            return base.Channel.EditGoal(GoalId, disciplineId, periodDays, value, description, ownerId);
        }
        
        public bool DeleteGoal(int GoalId) {
            return base.Channel.DeleteGoal(GoalId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Goals AddUsers_Goals(int userId, int goalId, System.DateTime dateStart) {
            return base.Channel.AddUsers_Goals(userId, goalId, dateStart);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Goals EditUsers_Goals(int Users_GoalsId, int userId, int goalId, System.DateTime dateStart) {
            return base.Channel.EditUsers_Goals(Users_GoalsId, userId, goalId, dateStart);
        }
        
        public bool DeleteUsers_Goals(int Users_GoalsId) {
            return base.Channel.DeleteUsers_Goals(Users_GoalsId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Data AddUsers_Data(int user_goalId, System.DateTime date, double value) {
            return base.Channel.AddUsers_Data(user_goalId, date, value);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users_Data EditUsers_Data(int user_dataId, int user_goalId, System.DateTime date, double value) {
            return base.Channel.EditUsers_Data(user_dataId, user_goalId, date, value);
        }
        
        public bool DeleteUsers_Data(int user_dataId) {
            return base.Channel.DeleteUsers_Data(user_dataId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Standart_Data AddStandart_Data(double value, int goalId, short day) {
            return base.Channel.AddStandart_Data(value, goalId, day);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Standart_Data EditStandart_Data(int standart_dataId, double value, int goalId, short day) {
            return base.Channel.EditStandart_Data(standart_dataId, value, goalId, day);
        }
        
        public bool DeleteStandart_Data(int standart_dataId) {
            return base.Channel.DeleteStandart_Data(standart_dataId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Users GetUserFromId(int userId) {
            return base.Channel.GetUserFromId(userId);
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Scales[] GetAllScales() {
            return base.Channel.GetAllScales();
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Sports[] GetAllSports() {
            return base.Channel.GetAllSports();
        }
        
        public Sportsmen_Monitoring.ServiceConnectServer.Discipline[] GetDiscipliniesFromSport(int sportId) {
            return base.Channel.GetDiscipliniesFromSport(sportId);
        }
    }
}
